language: c
sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
      #- g++
      #- gfortran
      #- valgrind
      #- csh
      #- g++-multilib
      #- gcc-multilib
branches:
  only:
    - master

install:
  - source devtools/travis-ci/install.sh
  - export PYTHONUNBUFFERED=true
#  - export CC=gcc
#  - export CXX=g++


script:
  - conda config --add channels ${ORGNAME}
  - conda build devtools/conda-recipe
  - source activate _test
  # Install test dependencies in test environment.
  - conda install --yes --quiet pip
  - pip install --upgrade pip
  - pip install nose nose-timer
  # Fix openmm double dependencies
  - conda remove --yes openmm openmm-dev && conda install --yes openmm-dev
  # Run tests
  #- cd devtools && nosetests $PACKAGENAME --nocapture --verbosity=3 --with-doctest --with-timer && cd ..
  - nosetests ${PACKAGENAME} -v --with-timer
  
env:
  matrix:
    - python=2.7 CONDA_PY=27 NOSETESTS="constph.tests.test_implicit"
    - python=2.7 CONDA_PY=27 NOSETESTS="constph.tests.test_explicit"
    - python=3.4 CONDA_PY=34 NOSETESTS="constph.tests.test_implicit"
    - python=3.4 CONDA_PY=34 NOSETESTS="constph.tests.test_explicit"
    - python=3.5 CONDA_PY=35 NOSETESTS="constph.tests.test_implicit"
    - python=3.5 CONDA_PY=35 NOSETESTS="constph.tests.test_explicit"
 
   global:
    - ORGNAME="omnia"
    - PACKAGENAME="constph"
        
after_success:
  - echo "after_success"
  # - if [ "$TRAVIS_SECURE_ENV_VARS" == true ]; then source devtools/travis-ci/after_success.sh; fi
