package:
  name: openmm-constph
  version: !!str 0.0.0

source:
  path: ../../

build:
  preserve_egg_dir: True
  number: 0

requirements:
  build:
    - python
    - openmm-dev
    - numpy
    - scipy
    - openmmtools-dev
    - pymbar
    - openmoltools-dev
    - ambermini

  run:
    - python
    - openmm-dev
    - numpy
    - scipy
    - openmmtools-dev
    - pymbar
    - openmoltools-dev
    - ambermini

test:
  requires:
    - nose
  imports:
    - constph

about:
  home: https://github.com/choderalab/openmm-constph
