name: constph
channels:
    - omnia
dependencies:
    - python
    - openmm ==7.0rc1
    - numpy >=1.10
    - scipy >=0.17.0
    - openmmtools ==0.7.5
    - pymbar
    - openmoltools ==0.7.0
    - ambermini
    - joblib
    - lxml